name: MLOps GitHub Actions
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  code-quality-checking:
    runs-on: self-hosted
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} self-hosted server."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: âš¡ Check out repository code
        uses: actions/checkout@v2

      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: ğŸ“„ List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: âœ… Code format checking with Black
        run: /home/ubuntu/.virtualenvs/githubenv/bin/black --check .

      - name: âœ… Import order checking with Isort
        run: /home/ubuntu/.virtualenvs/githubenv/bin/isort --check .

      - name: âœ… Code style checking with Flake8
        run: /home/ubuntu/.virtualenvs/githubenv/bin/flake8

      - name: âœ… Static type checking with Mypy
        run: /home/ubuntu/.virtualenvs/githubenv/bin/mypy .

      - name: âœ… Doc style checking with Pydocstyle
        run: /home/ubuntu/.virtualenvs/githubenv/bin/pydocstyle

      - run: echo "ğŸ This job's status is ${{ job.status }}."

  code-pushing:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
    - name: âš¡ Check out repository code
      uses: actions/checkout@v2

    - name: â™»ï¸ Synchronize Airflow dags and plugins to EC2
      run: |
        rsync -av --exclude '*__pycache__*' --delete airflow/dags/ /home/ubuntu/airflow/dags
        rsync -av --exclude '*__pycache__*' --delete airflow/plugins/ /home/ubuntu/airflow/plugins

    - run: echo "ğŸ This job's status is ${{ job.status }}."
